name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  run-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: ${{ secrets.VERSIONING_TOKEN }}
        with:
          publish_latest_tag: 'true'
